
<?php 

echo "<div id='wrapper'>"
	."<div id='main'>"
	."<header>"
		."<a href='index.php'><img class='logo' src='images/redcross.png' alt='Melbourne Red Cross'></a>" 
		."<nav>"
		."<ul class='nav_links'>"
		."<li><a href='index.php'>Home</a></li>" 
		."<li><a href='position.php'>Vacancies</a></li>" 
		."<li><a href='apply.php'>Apply</a></li>" 
		."<li><a href='detail.php'>Profile</a></li>"
		."<li><a href='registration.php'>Sign Up</a></li>"
		."<li><a href='login.php'>Login</a></li>"
		."<li><a href='enhancements.php'>En</a></li>"
		."<li><a href='enhancements2.php'>En JS</a></li>"
		."<li><a href='phpenhancements.php'>En PHP</a></li>"
	."</ul>"
	."</nav>"
	."<div class='theme_togglewrapper'>"
	."<button id='theme_switch'>Light Theme</button>"
	."<button id='theme_switch_default'>Dark Theme</button>"
."</div>"
    ."</header>";
    
    ?>